apiVersion: v1
kind: Service
metadata:
  name: kong-dp
  namespace: kong
spec:
  type: NodePort
  ports:
    - name: proxy
      port: 8000
      targetPort: 8000
      nodePort: 30800  # ALB will target this port on EC2 nodes
    - name: proxy-ssl
      port: 8443
      targetPort: 8443
      nodePort: 30843
    - name: status
      port: 8100
      targetPort: 8100
      nodePort: 30810  # For health checks
  selector:
    app: kong-dp

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong-dp
  namespace: kong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kong-dp
  template:
    metadata:
      labels:
        app: kong-dp
    spec:
      containers:
        - name: kong
          image: kong:3.6
          env:
            - name: KONG_LOG_LEVEL
              value: "error"
            - name: KONG_STATUS_LISTEN
              value: 0.0.0.0:8100
            - name: KONG_DNS_RESOLVER
              value: 10.43.0.10:53 # dns server ip inside k8s cluster
            - name: KONG_DATABASE
              value: "off"
            - name: KONG_ROLE
              value: "data_plane"
            - name: KONG_CLUSTER_CONTROL_PLANE
              value: "kong-cp.kong.svc.cluster.local:8005"
            - name: KONG_PROXY_ACCESS_LOG
              value: "/dev/stdout"
            - name: KONG_PROXY_ERROR_LOG
              value: "/dev/stderr"
            - name: KONG_CLUSTER_CERT
              value: "/kong-cluster/tls.crt"
            - name: KONG_CLUSTER_CERT_KEY
              value: "/kong-cluster/tls.key"
          ports:
            - containerPort: 8000
            - containerPort: 8443
            - containerPort: 8100
          volumeMounts:
            - name: kong-cluster-cert
              mountPath: /kong-cluster
              readOnly: true
      volumes:
        - name: kong-cluster-cert
          secret:
            secretName: kong-cluster-cert