apiVersion: v1
kind: Service
metadata:
  name: service-a
  namespace: default
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: service-a

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-a
  template:
    metadata:
      labels:
        app: service-a
    spec:
      containers:
        - name: http-echo
          image: hashicorp/http-echo
          args:
            - "-text=Hello from service-a"
          ports:
            - containerPort: 8080