apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  namespace: ingress-nginx
  labels:
    app: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: demo
        image: hashicorp/http-echo
        args:
        - "-text=hello from demo"
        ports:
        - containerPort: 5678
---
apiVersion: v1
kind: Service
metadata:
  name: demo
  namespace: ingress-nginx
spec:
  ports:
  - port: 80
    targetPort: 5678
  selector:
    app: demo
  type: ClusterIP