apiVersion: apps/v1
kind: Deployment
metadata:
  name: myflask-deployment
spec:
  selector:
    matchLabels:
      app: myflask
  template:
    metadata:
      labels:
        app: myflask
    spec:
      containers:
      - name: myflask-app
        image: myflask-app:v1
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
      imagePullSecrets:
      - name: ecr-secret
      envFrom:
      - configMapRef:
          name: myflask-configmap