apiVersion: v1
kind: Service
metadata:
  name: myflask-service
spec:
  type: NodePort  # Optional (default)
  selector:
    app: myflask  # Matches pods with this label
  ports:
    - protocol: TCP
      port: 8080       # Service port
      targetPort: 80 # Pod port
      nodePort: 30080  # Optional (default: 30000-32767)